### ISSUE TITLE
Research/Create Twitter sentiment program to scan tweets using API

### ISSUE THREAD

**Issue by gnarayan1337** [CSAllenISD/2023-ISP-FreeCash#5]
Need to research and read Twitter API documentation. After I have learned the Twitter API I need to make a simple program that scrapes for the last 100-300 tweets that contain "$xxxx".

**Comment by squaredcubed64** [comment]
Make sure you know how many tweets the Twitter API will let you scrape. We may need a lot of tweets to train our model before it understands tweet sentiments.

**Comment by squaredcubed64** [comment]
The Twitter API allows 500,000 requests per month, which should be enough for us. Also, twitterscraper.py successfully scrapes recent tweets that contain a given stock ticker.
